architect:
  - maxonfjvipon
docker:
  as_root: true
install:
  - "sudo apt-get update"
merge:
  commanders:
    - maxonfjvipon
  script: |-
    composer validate --strict
    
    apt-get install php-xml php-mbstring php-xdebug -y
    
    echo 'xdebug.mode=coverage' >> /etc/php/8.1/cli/php.ini
    
    composer install --prefer-dist --no-progress
    
    ./pre-push.sh
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    
    composer validate --strict
    
    apt-get install php-xml php-mbstring php-xdebug -y
    
    echo 'xdebug.mode=coverage' >> /etc/php/8.1/cli/php.ini
    
    composer install --prefer-dist --no-progress
    
    ./pre-push.sh
