architect:
  - maxonfjvipon
docker:
  as_root: true
merge:
  commanders:
    - maxonfjvipon
  script: |-
    composer validate --strict
    
    add-apt-repository ppa:ondrej/php -y
    
    sudo apt-get update
    
    apt install php8.1 -y
    
    apt-get install php8.1-{xml,mbstring,xdebug} -y
    
    sudo update-alternatives --set php /usr/bin/php8.1
    
    echo 'xdebug.mode=coverage' >> /etc/php/8.1/cli/php.ini
    
    composer install --prefer-dist --no-progress
    
    ./pre-push.sh
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    
    composer validate --strict
    
    add-apt-repository ppa:ondrej/php -y
    
    sudo apt-get update
    
    apt install php8.1 -y
    
    apt-get install php8.1-{xml,mbstring,xdebug} -y
    
    sudo update-alternatives --set php /usr/bin/php8.1
    
    echo 'xdebug.mode=coverage' >> /etc/php/8.1/cli/php.ini
    
    composer install --prefer-dist --no-progress
    
    ./pre-push.sh
