architect:
  - maxonfjvipon
merge:
  commanders:
    - maxonfjvipon
  script: |-
    echo "Validate composer..."
    composer validate --strict
    echo "Run composer..."
    composer install --prefer-dist --no-progress
    echo "PHPStan..."
    composer run-scripts phpstan
    echo "PHPUnit..."
    composer run-scripts tests
release:
  commanders:
    - maxonfjvipon
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    echo "Validate composer..."
    composer validate --strict
    echo "Run composer..."
    composer install --prefer-dist --no-progress
    echo "PHPStan..."
    composer run-scripts phpstan
    echo "PHPUnit..."
    composer run-scripts tests
